# Generated by Django 3.1.2 on 2020-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=60)),
                ('sub_category', models.CharField(max_length=60)),
                ('model_number', models.CharField(max_length=60)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('site', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(verbose_name='Last Updated')),
                ('details', models.TextField(verbose_name='Product Details')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Data',
        ),
    ]
