# Generated by Django 3.1.2 on 2020-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_auto_20201012_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='permalink',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
