# Generated by Django 3.1.2 on 2020-10-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.FileField(upload_to='uploads/')),
                ('product_categories', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Toys & Baby', 'Toys & Baby'), ('Beauty', 'Beauty'), ('Sports & Exercise', 'Sports & Exercise'), ('Grocery', 'Grocery')], max_length=60)),
                ('url', models.URLField()),
                ('seller_name', models.CharField(blank=True, max_length=60)),
                ('in_stock', models.CharField(choices=[('Yes', 'In Stock'), ('No', 'Out of Stock')], max_length=20)),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_color', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('submitted', models.DateField(auto_now_add=True)),
                ('quotedate', models.DateField(blank=True, null=True)),
                ('product_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
