# Generated by Django 3.1.2 on 2020-10-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='product_key',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='web',
        ),
    ]
