# Generated by Django 3.1.2 on 2020-10-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20201020_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
